### ISSUE TITLE
ids must be unique for each page

### ISSUE THREAD

**Issue by splatterxl** [dcrime/WBBD#1]
https://github.com/dcrime/WBBD/blob/32360987cec44eacd83365470c5a72b4d692524d/Visuals/style.css#L257 I first noticed it here.

Using IDs for identifying non-unique elements
1. does not work
1. is bad practise.

**Comment by maalos** [comment]
1.why?
2. daniel made everything an ID so i continued

**Comment by dcrime** [comment]
@nearlySplat I agree with your point, and I actually used a class only once `guild`, however it was in main.js so I can't really blame @maalos  for not seeing it

I also didn't look at the html since my main focus was on functionality, even if the order is a bit weird

**Comment by dcrime** [comment]
ID's are being changed as they're being used in the code, so I'm closing this issue

**Comment by splatterxl** [comment]
> 1.why?

@maalos it doesn't work as only one of the elements would have the ID set on them, leading to a 
```html
<div id=message></div>
<!-- this should also be a message, but because of the ID, it's not -->
<div></div>
```

(sorry for the late reply btw)
